CREATE TABLE CLIENTE(
ID_CLIENTE SERIAL, -- GENERATED_VALUE IDENTITY
NOME VARCHAR(45) NOT NULL,
CPF VARCHAR(45) UNIQUE NULL,
CNPJ VARCHAR(45) UNIQUE NULL,
TIPO_CLIENTE VARCHAR(45) NOT NULL,
CONSTRAINT CLIENTE_PK PRIMARY KEY(ID_CLIENTE),
CONSTRAINT CHECK_TIPO_CLIENTE CHECK (TIPO_CLIENTE IN ('PF','PJ'))
);

CREATE TABLE CLIENTE_EMAIL(
ID_CLIENTE INT,
EMAIL VARCHAR(50),
CONSTRAINT CLIENTE_EMAIL_PK PRIMARY KEY(ID_CLIENTE, EMAIL),
CONSTRAINT CLIENTE_EMAIL_CLIENTE_FK FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE CLIENTE_TELEFONE(
ID_TELEFONE INT,
TELEFONE VARCHAR(20) NOT NULL,
NOME_CONTATO VARCHAR(50) NOT NULL,
APELIDO_CONTATO VARCHAR(20) NOT NULL,
ID_CLIENTE INT NOT NULL,
CONSTRAINT CLIENTE_TELEFONE_PK PRIMARY KEY(ID_TELEFONE),
CONSTRAINT CLIENTE_TELEFONE_CLIENTE_FK FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE SEQUENCE ID_TELEFONE_SEQUENCE OWNED BY CLIENTE_TELEFONE.ID_TELEFONE;

CREATE TABLE PRODUTO(
ID_PRODUTO BIGINT, -- GENERATED_VALUE SEQUENCE
DESCRICAO VARCHAR(200),
VALOR DOUBLE PRECISION NOT NULL,
CONSTRAINT PRODUTO_PK PRIMARY KEY(ID_PRODUTO)
);

CREATE SEQUENCE ID_PRODUTO_SEQUENCE OWNED BY PRODUTO.ID_PRODUTO;

CREATE TABLE FORNECEDOR(
ID_FORNECEDOR INT, -- GENERATED_VALUE SEQUENCE
NOME VARCHAR(45) NOT NULL UNIQUE,
CONSTRAINT FORNECEDOR_PK PRIMARY KEY(ID_FORNECEDOR)
);

CREATE SEQUENCE ID_FORNECEDOR_SEQUENCE OWNED BY FORNECEDOR.ID_FORNECEDOR;

CREATE TABLE FORNECEDOR_PRODUTO(
FORNECEDOR_ID_FORNECEDOR INT,
PRODUTO_ID_PRODUTO BIGINT,
CONSTRAINT FORNECEDOR_PRODUTO_PK PRIMARY KEY(FORNECEDOR_ID_FORNECEDOR, PRODUTO_ID_PRODUTO),
CONSTRAINT FORNECEDOR_PRODUTO_FORNECEDOR_FK FOREIGN KEY(FORNECEDOR_ID_FORNECEDOR)
REFERENCES FORNECEDOR(ID_FORNECEDOR) ON DELETE CASCADE,
CONSTRAINT FORNECEDOR_PRODUTO_PRODUTO_FK FOREIGN KEY(PRODUTO_ID_PRODUTO)
REFERENCES PRODUTO(ID_PRODUTO) ON DELETE CASCADE
);

CREATE TABLE PEDIDO(
ID_PEDIDO BIGINT, -- GENERATED_VALUE SEQUENCE
DATA TIMESTAMP NOT NULL,
CLIENTE_ID_CLIENTE INT NOT NULL,
CONSTRAINT PEDIDO_PK PRIMARY KEY(ID_PEDIDO),
CONSTRAINT PEDIDO_CLIENTE_FK FOREIGN KEY(CLIENTE_ID_CLIENTE) 
REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE SEQUENCE ID_PEDIDO_SEQUENCE OWNED BY PEDIDO.ID_PEDIDO;

CREATE TABLE ITEM_PEDIDO(
PEDIDO_ID_PEDIDO BIGINT,
PRODUTO_ID_PRODUTO INT,
QUANTIDADE INT NOT NULL,
CONSTRAINT ITEM_PEDIDO_PK PRIMARY KEY(PEDIDO_ID_PEDIDO, PRODUTO_ID_PRODUTO),
CONSTRAINT ITEM_PEDIDO_PEDIDO_FK FOREIGN KEY(PEDIDO_ID_PEDIDO) 
REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE,
CONSTRAINT ITEM_PEDIDO_PRODUTO_FK FOREIGN KEY(PRODUTO_ID_PRODUTO)
REFERENCES PRODUTO(ID_PRODUTO) ON DELETE SET NULL
);

CREATE TABLE DEPENDENTE(
RG VARCHAR(30) NOT NULL UNIQUE,
ID_CLIENTE INT NOT NULL,
NOME VARCHAR(50) NOT NULL,
CONSTRAINT DEPENDENTE_PK PRIMARY KEY (RG, ID_CLIENTE),
CONSTRAINT DEPENDENTE_CLIENTE_FK FOREIGN KEY (ID_CLIENTE) 
	REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE 
);